# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Unit Tests'
  inputs:
    command: 'custom'
    verbose: false
    customCommand: 'run test-unit'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'HazzatWebBuildPpe'
    publishLocation: 'Container'